---
- name: Docker | Download GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Docker | Add apt source
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_facts['distribution_release'] }} stable
    state: present

- name: Docker | Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Docker | Enable and start docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Docker | Enable and start containerd service
  become: true
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true

- name: Docker | Add the user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true
